TESTCASE_START EmergencyLoggingTest.ttcn:17 Test case tc_user_EL started.
ACTION_UNQUALIFIED EmergencyLoggingTest.ttcn:22 Action: >>>>ACTION in tc_user_EL, before the loop<<<<<
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 9
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 10
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 11
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 12
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 13
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 14
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 15
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 16
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 17
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 18
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:24 tc_user_EL loop 19
ACTION_UNQUALIFIED EmergencyLoggingTest.ttcn:26 Action: >>>>ACTION in tc_user_EL, after the loop<<<<<
VERDICTOP_SETVERDICT EmergencyLoggingTest.ttcn:27 setverdict(pass): none -> pass
USER_UNQUALIFIED EmergencyLoggingTest.ttcn:28 This line is reached last
ERROR_UNQUALIFIED EmergencyLoggingTest.ttcn:29 Dynamic test case error: Assignment of an unbound integer value.
TESTCASE_FINISH EmergencyLoggingTest.ttcn:29 Test case tc_user_EL finished. Verdict: error
